name: Java Deployment

on:
  push:
    branches: [master]


jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with maven
        run: mvn clean package -DskipTests

      - name: Deploy application
        run: |
          pm2 stop notification-application || true
          pm2 delete notification-application || true
          pm2 start ecosystem.config.js

      - name: Save PM2 process list and environment
        run: |
          pm2 save